### ISSUE TITLE
Attempting to use mirror out of range breaks game

### ISSUE THREAD

**Issue by Maytwa** [DArkHekRoMaNT/TemporalMirror#2]
I attempted to use a gold (4k) mirror at about 8k and several game mechanics stopped working.  I no longer took fall damage, air wasn't used or displayed under water, mobs ignored me, the vanilla teleporters stopped functioning.  Probably other issues as well.

**Comment by RogueRaiden** [comment]
spams this error
https://pastebin.com/3vF6RK3j

**Comment by DArkHekRoMaNT** [comment]
Lol
![image](https://user-images.githubusercontent.com/15899143/197286011-37605d49-736d-416e-887d-8eead88b7160.png)
But it doesn't crash anymore, yeah 🤣

**Comment by DArkHekRoMaNT** [comment]
Fixed in 1.7.0
